name: haikukigo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:

  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  flutter_riverpod: ^2.0.1
  font_awesome_flutter: ^10.2.1
  freezed_annotation: ^2.1.0
  grouped_list: ^5.1.2
  http: ^0.13.5
  json_annotation: ^4.6.0
  tab_container: ^2.0.0

dev_dependencies:

  build_runner: ^2.2.0

  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

  freezed: ^2.0.4

  json_serializable: ^6.3.1

flutter:

  uses-material-design: true
